### ISSUE TITLE
Lumber count

### ISSUE THREAD

**Issue by Jingah** [MNoya/DotaCraft#1]
hey, I just implemented lumber in my Addon, but facing a problem right now:
In the UI it doesn't show me the lumber, it looks like the following

![unbenannt](https://cloud.githubusercontent.com/assets/11037774/6267868/2bb9cef6-b848-11e4-961b-4c880fa2452c.jpg)

Hope you can help me

**Comment by MNoya** [comment]
Seems like I didn't embed the font properly, the font used by the gold display which I copied to the lumber overlay is named Radiance, you can download it here: https://moddota.com/resources/DotaFonts.rar

**Comment by Jingah** [comment]
Okay thanks, do I need to put this in a specific folder or just in the resource folder?

**Comment by MNoya** [comment]
Just Install it and it should work. Anyways I'll update the CustomUI.swf with the embedded font now so installing the font isn't necessary.

**Comment by Jingah** [comment]
Well okay, I used your edited files now from the newest commit, but still don't get the font in there.
In the console I get following error
![unbenannt2](https://cloud.githubusercontent.com/assets/11037774/6270972/ec745c32-b85d-11e4-936b-17765f99b3f1.jpg)

**Comment by MNoya** [comment]
I committed another attempt to fix it by disabling the export for actionscript and also writing the whole 1234567890 string so the game might load the characters that way.

**Comment by Jingah** [comment]
Well no, I copied these files into my addon, but still no number is displayed. It only works when installing these fonts ...
