### ISSUE TITLE
Add computer slots

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#103]
When loading into a map, the screen should show all the empty slots (for the map playercount of that map), and have an option for Computer (Easy)/(Medium)/(Hard), which will create a fake client/bot that does (initially) some very basic AI actions.

**Comment by ghost** [comment]
<b>Progress Update:</b> 18/12/15 @ 15:20
![current_wip](https://cloud.githubusercontent.com/assets/8635337/11900132/ae29fa0a-a59b-11e5-827f-982efc5f992d.png)
![computer_assignment_demo](https://cloud.githubusercontent.com/assets/8635337/11900131/ae26231c-a59b-11e5-92d5-de1a290cf6a9.gif)

<b>Implementations:</b>
Added computer slots
Added Template slots - open by default - players will be able to sit(not current implement) -  (host can assign ai)
Started Refractoring code
Added TeamSelection Object

<b>To-Do:</b>
Refractor code
Implement lua-side AI handling
expand functionality of nettable
Implement players to sit at a specied slot.
Implement a button for players to leave their current slot
Implement a spectator label or panel at the top, so you can see who is unassigned
Fix chatbox - essentially make it visible and be able to be use,
Any other functionality identified at a later time

Leave criticism and feedback down below or in IRC.

**Comment by ghost** [comment]
<b>Progress Update:</b> 19/12/15 @ 16:36
No Images

<b>Implementations:</b>
New Nettable -> dotacraft_pregame_table - | Team | Color | Race | PlayerID | PanelID |
Refractored code - still WIP
Deprecated some of the left-over ready up functionality inside player setup
Added new nettable listener
Removed local vars in player, instead all connected to Root Panel.
Re-Worked how players were being made

<b>To-Do:</b>
Refractor code
Implement lua-side AI handling
Implement players to sit at a specied slot.
Implement a button for players to leave their current slot
Implement a spectator label or panel at the top, so you can see who is unassigned
Fix chatbox - essentially make it visible and be able to be use,
Any other functionality identified at a later time

Leave criticism and feedback down below or in IRC.

**Comment by ghost** [comment]
Completed asof next commit (incoming later today or tomorrow)
-- some of the To-Do's are still not completed but as far as the specific issue goes this is completed, I have noted the remaining to-do's down obv.
