### ISSUE TITLE
Peasant doesn't build if queued to do something afterwards

### ISSUE THREAD

**Issue by justSQL** [MNoya/DotaCraft#104]
**Summary:**

A peasant (As i've only tested Human) skips building whatever it was supposed to build if queued to perform any other action after that.

**Repro Steps:**
1. Order a peasant to build anything (Like a farm)
2. Queue the peasant to, for example, walk somewhere before it starts building the building.

**Result:**

Peasant swings his sword once but never starts building anything, just moves to where you queued it to.

**Expected Result:**

Peasant starts, and finishes building the structure before doing what was queued after that.

**Comment by MNoya** [comment]
Related to #72

**Comment by MNoya** [comment]
fucking blue-darkblue labels
