### ISSUE TITLE
Backpack seems completely broken

### ISSUE THREAD

**Issue by justSQL** [MNoya/DotaCraft#105]
**Summary:**

Backpack doesn't seem to be working at all. Researching it does not grant the units the possibility to carry items. Also, as a side note, selling the backpack-items (the ones that look like locks) in your units inventory is possible when near a shop, which shouldn't be the case.

**Repro Steps:**
1. Research the backpack - ability
2. Try to buy something with a unit who should be able to do so now (Like a footman)

**Result:**

The shop says "No valid buyers in range" and you can't buy anything.

**Expected Result:**

Being able to carry items with the units that have backpack.

**Comment by MNoya** [comment]
It actually works for Orcs, Night Elves and Undeads
