### ISSUE TITLE
Annoying sound when you don't have enough food

### ISSUE THREAD

**Issue by Coolkip** [MNoya/DotaCraft#109]
When you queue units in the baracks (only tested with humans) and you don't have enough food to continue the process, you will keep hearing an annoying sound (the sound you get when clicken on a not learned ability). It stops as soon as you build new farms.
1. build baracks
2. queue units
3. make sure you don't have enough farms to support all the units
4. enjoy the sound

**Comment by justSQL** [comment]
Yeah, this is a really annoying issue.
