### ISSUE TITLE
Incorrect lumber display when drawing minimap on right

### ISSUE THREAD

**Issue by ssnl** [MNoya/DotaCraft#11]
**Summary:**

When drawing minimap on right, the lumber number is shown over the minimap

**Repro Steps:**
1. Set minimap on right
2. Start a game!

**Result:**

lumber is shown on right over the minimap.

**Expected Result:**

lumber is shown on left.

**Comment by MNoya** [comment]
WC3 didn't have the option to put the minimap on the right :smile:

We might end up putting the Gold Lumber Food display on Top Left, so that the Gold shows at all times (currently when you select an enemy unit it doesn't get displayed on default dota UI)

![img](http://puu.sh/jYwGN/11d245af44.jpg)
