### ISSUE TITLE
Building grid can get permanently "stuck" in the map

### ISSUE THREAD

**Issue by justSQL** [MNoya/DotaCraft#116]
**Summary:**

You can cause the building grid to "get stuck" / "paint" itself to the map. [Here's a video that shows this better.](http://sendvid.com/hwxuvpou) (Hope you don't mind the lagginess my videos have, OBS settings are really f*cked up.)

**Repro Steps:**
1. Hold down alt and press the hotkey for building any building (so that you get the building ghost and the grid visible)
2. Keep holding the alt button, and press a hotkey for another building
3. The grid should now be permanently stuck on the map

**Result:**

Grid gets "stuck" / "painted" on where your cursor was when you changed the building.

**Expected Result:**

The grid to not get stuck on the map.

**Comment by MNoya** [comment]
Nice find, I'm forgetting to clear an array of particles in there
