### ISSUE TITLE
Melting Valley Neutral Creeps

### ISSUE THREAD

**Issue by TwiGzZz** [MNoya/DotaCraft#122]
Here is a list of all neutral creeps that are used in the map Melting Valley. Some of them are already in the files. The rest needs to be added.
- [x] Gnoll Warden
- [x] Gnoll Overseer
- [x] Gnoll Poacher
- [x] Gnoll Assassin
- [x] Gnoll Brute
- [x] Ogre Lord
- [x] Ogre Mauler
- [x] Ogre Magi
- [x] Ice Troll Trapper
- [x] Ice Troll High Priest
- [x] Ice Troll Berserker
- [x] Ice Troll Warlord
- [x] Ice Troll
- [x] Murloc Nightcrawler
- [x] Murloc Huntsmen
- [x] Murloc Tiderunner
- [x] Rock Golem
- [x] Granite Golem

**Comment by MNoya** [comment]
Can I use Arc Warden for Gnoll Warden model? Full circle etc

**Comment by MNoya** [comment]
Let me know if I missed anything
