### ISSUE TITLE
Shops Nettable exceeding size allowed

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#134]
Building up to 5-10 shops will exceed the nettable size.

Need to come up with solutions either;
Restriction shops per player(which is not really what we want)
Or
Change from nettable to gameEvents

kudos to VicFrank for pointing it out.

**Comment by MNoya** [comment]
Game Events seem solid, scheduling the stock inside .js would alleviate much of the current networking. Just need to make sure everything is requested again on reconnect

**Comment by MNoya** [comment]
More conclusive report at #145
