### ISSUE TITLE
Group testing

### ISSUE THREAD

**Issue by Arhowk** [MNoya/DotaCraft#14]
We need to organize some 1v1s, 2v2s, or even 3v3s if its stable enough

**Comment by leedarhed** [comment]
Count me in :)! **if its stable enough**

**Comment by Arhowk** [comment]
Petar, sign up here first https://github.com/MNoya/DotaCraft/wiki/Alpha-Testing-Team

**Comment by leedarhed** [comment]
I'm there but with the nickname I use in Steam and ModDota: "leedarhed" ^^

**Comment by MNoya** [comment]
We need a Steam Group, I'll get right on it

Or rather use https://steamcommunity.com/groups/ModDota for now

**Edit:** https://steamcommunity.com/groups/dota-craft/ (Don't use it, all good names were taken :smile: )

**Comment by Arhowk** [comment]
Noya does 6pm est tomorrow work for you? id prefer to have a developer there :P

**Comment by MNoya** [comment]
You are all developers :smile:
Won't be available today, but feel free to do 1v1s should go well

**Comment by Arhowk** [comment]
Not a developer of dc q.q
