### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#146]
```
LUA Memory usage warning: The VM has hit a new high usage of 2,133,852,160 bytes.
Script Runtime Error: not enough memory
Disconnected From 'Localhost:29000'
```

![img](https://i.imgur.com/SLqKhQq.png)

**Comment by MNoya** [comment]
Identified one issue: [modifier_specially_deniable.lua](https://github.com/MNoya/DotaCraft/blob/master/game/dota_addons/dotacraft/scripts/vscripts/libraries/modifiers/modifier_specially_deniable.lua), removing it on unit spawns stopped much of the memory usage increase messages inside tools, but some leak still remains, more noticeable in the main client.

**Comment by MNoya** [comment]
Ok, it's still leaking but way slower, can live with it for the moment.

**Comment by justSQL** [comment]
I actually measured just how fast it still leaks; hit [ W VScript              ]: LUA Memory usage warning: The VM has hit a new high usage of 188,743,680 bytes. in 40 minutes. Like you said, it's not too bad.

Edit: This may actually no longer be the case, i measured this two days ago and i'm not sure how much better the latest commit referencing this issue may have made it.
