### ISSUE TITLE
AI group aggro

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#150]
it seems group camps that are relatively spread don't aggro as a group.

![beforepull](https://cloud.githubusercontent.com/assets/8635337/11968992/227f32ea-a90b-11e5-813c-2bc95902ff93.jpg)
![afterpull](https://cloud.githubusercontent.com/assets/8635337/11968991/227daa1a-a90b-11e5-93a3-6e86943100ca.png)

A solution could be that all units made for a camp are added to an array and each array holds references to the units of said group, and a :IsAggro() check could force all members of that group to force attack a target?

**Comment by MNoya** [comment]
I need to play around `AlertNearbyUnits` and `AngerNearbyUnits` to overall improve the aggro system. Checking group aggro could, although the neutral AI wasn't designed to work 100% as a group (I think it doesn't do this in wc3 even, you are still able to lure some units away from the group if you trick the AI)

**Comment by MNoya** [comment]
Fixed in 12114aaaf22844efaa57da8f6afcb9537f1c25d4
