### ISSUE TITLE
Spectator UI Mirror - future

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#151]
Implement enhanced functionality to most UI elements in order to allow spectators to mirror panels from their selected player:
- [ ] Player Resources Mirrored
- [ ] Tavern Mirrored
- [ ] Unit Shop Mirrored
- [ ] Hero Panel Mirrored

**Comment by MNoya** [comment]
If this is too hard/unpractical, perhaps it would be better to just have a full spectator UI (see WC3 WCA overlays for reference)
