### ISSUE TITLE
Mutli-unit creation based on same-type building selections

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#157]
In WC3 it's an mechanic where multiple-selections of the same type of building  allow for issuing of multiple unit build orders (through hotkey) creates a unit in both(or more) instances.

Dotocraft:
Select 2 Barracks, click q to make unit
Outcome: 1 unit is queued.

WC3:
Select 2 Barracks, click q to make unit
Outcome: 2 units are queued.

**Comment by MNoya** [comment]
This seems easy to implement with the `"AbilityMultiOrder" "1"` system, just need to make sure there are enough resources to cast on the secondary units
