### ISSUE TITLE
Tavern/Shop Errors

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#167]
A list of errors identified for tavern/shop.
- [x] Players can buy items regardless of current gold/lumber, but will subtract to 0.
  need to double-check the buy function

( part fault of developer mode I suspect )
- [x] Hero panels are not correctly deleted from the tavern (doctorgester)
  need to double-check the buy function to properly send the delete_panel command, likewise for altar.
- [x] Players can purchase multiple heroes from tavern if clicked fast enough 81ea0b9d0dd3eb6ac3d9d5a88148fbd02fe26e81

Can buy all heroes of tavern if clicked fast enough need a hero counter to limit this.

We need an incrementation on lua side to disallow hero spam-click, pref a hero counter that increments with each trained/bought hero and using htis counter inside the buy function of the shop to limit this spam-clicking

@MNoya 
https://github.com/MNoya/DotaCraft/blob/DotaCraft-UI/game/dota_addons/dotacraft/scripts/vscripts/buildings/shop.lua#L332-L344

**Comment by ghost** [comment]
I believe this is the correct solution.

**Comment by MNoya** [comment]
We can use `Players:CanTrainMoreHeroes(playerID)` and `Players:HeroCount(playerID)`

https://github.com/MNoya/DotaCraft/blob/DotaCraft-UI/game/dota_addons/dotacraft/scripts/vscripts/mechanics/players.lua#L575-L582

We really need to build a custom API page to keep track of all these functions :smile:

**Comment by MNoya** [comment]
- [x] Hero revives are being added to every shop

![img](http://puu.sh/mhnrW/6cdca3d9ab.jpg)

**Comment by ghost** [comment]
Fixed hero panels getting made in all shop: https://github.com/MNoya/DotaCraft/commit/a80bda95aaf13dd9b5935bafef1b0d822329c87a.

**Comment by Infekma** [comment]
Fixed hero panels getting made in all shops.
