### ISSUE TITLE
Confirm whether debuff effects are ability-specific

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#201]
https://github.com/MNoya/DotaCraft/commit/89fbdf28f3fa94d7320cb67a863c6948442250ca has raised the question as to whether most debuff effects are applied to base or overall values, needs confirmation.
- [x] Confirm if debuff effects placed on units only affect base values
- [x] Necromancer Cripple
- [x] Firelord Soul Burn
- [x] Pit Lord How of Terror

**Comment by MNoya** [comment]
Cripple reduces base damage [confirmed](http://puu.sh/mt07q/56fe72e368.jpg)
