### ISSUE TITLE
Hotkeys - Control Group Tracking

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#203]
![ctrl-group-tracking](https://cloud.githubusercontent.com/assets/8635337/12323659/3ee413f4-bab5-11e5-9163-0c09ab4ba9ba.png)
Source: https://github.com/MNoya/DotaCraft/commit/ed5a244017a475563d2dd42a4de27baf9abe4e59

Just implemented control group tracking, hotkey listeners(when you press 1-9 NO CTRL) are dynamically created inside each panel based on the assigned index.

This issue is more about the creation hotkeys which consist of CTRL+1-9, firstly is it possible and secondly should we just hardcode each function or is there some form of key capable of being attached to the triggered event.

currently temp keys are:
1 - create group 1
2 - select group 1
.. etc (untill group 3)

Feel free to leave other criticism, such as for design choice or additional features required.

**Comment by MNoya** [comment]
Stuff to add:
- [x] `IsControlDown` usage
- [x] Images indicating which unit is each group associated with (heroes take priority, then unit count)
- [x] Double pressed -> relocate camera
