### ISSUE TITLE
Call to arms while repairing 

### ISSUE THREAD

**Issue by ghost** [MNoya/DotaCraft#210]
> [   Developer            ]: ...dota_addons\dotacraft\scripts\vscripts\units\builder.lua:1322: attempt to index local 'caster' (a nil value)
> [   Developer            ]: stack traceback:
> [   Developer            ]:     ...dota_addons\dotacraft\scripts\vscripts\units\builder.lua:1322: in function <...dota_addons\dotacraft\scripts\vscripts\units\builder.lua:1318>
> [ W VScript              ]: Script Runtime Error: ...dota_addons\dotacraft\scripts\vscripts\units\builder.lua:1322: attempt to index local 'caster' (a nil value)
> [ W VScript              ]: stack traceback:
> [ W VScript              ]:     ...dota_addons\dotacraft\scripts\vscripts\units\builder.lua:1322: in function <...dota_addons\dotacraft\scripts\vscripts\units\builder.lua:1318>

Seems a timer or thinker keeps calling the repair function despite the worker being called to arms!

Thanks to SQL for finding this.

**Comment by MNoya** [comment]
That is a ton of labels :stuck_out_tongue: 
Should be a problem with forgetting to remove the builders from the repairing list while sending them in call to arms, but I needed to refactor Repair anyway
