### ISSUE TITLE
Add fake players on Computer filled slots

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#218]
Current entry point in ui/pre_game.lua https://github.com/MNoya/DotaCraft/blob/master/game/dota_addons/dotacraft/scripts/vscripts/ui/pre_game.lua#L35

While at it, also need to rethink how this lua was split in #209 because it's currently not really clear and fractured in too many files

**Comment by ghost** [comment]
the initial refractoring idea was to localise each UI module that uses any form of lua to it's own file, while using main_ui.lua to require such files/house globally used functionality, although this does present some files that house purely 1 functionality from said UI module, so perhapse it could be done better

**Comment by MNoya** [comment]
Basic AI will be done at some point.
