### ISSUE TITLE
Storm's Windwalk invisibility lasts until the attack lands

### ISSUE THREAD

**Issue by dun1007** [MNoya/DotaCraft#22]
Summary : 
Refer to title

Procedure : 
1. Storm Earth and Fire heed my call
2. Select Storm and use Windwalk
3. Autoattack any target

Result : 
Storm remains invisible until the projectile actually hits(in other words, he will remain perma invis until his next autoattack lands)

Expected result : 
Invis should be removed as soon as backswing starts

Additional note : 
The code was copypasta'd from Blademaster's Windwalk who is not ranged. Requires slightly different approach for ranged hero

**Comment by MNoya** [comment]
OnAttack should be enough for Ranged Hero (it triggers when the attack is actually fired)

**Comment by dun1007** [comment]
If you remove modifier at OnAttack you won't reach the part where you deal bonus damage OnAttackLanded, perhaps make different modifier and place the damage and particle part there
