### ISSUE TITLE
Night Elf Wisps don't react to the "Select all other units" hotkey

### ISSUE THREAD

**Issue by justSQL** [MNoya/DotaCraft#247]
Using the Select all other units hotkey should select every unit that is not your main hero, and it does so for Human, Orc and Undead builders. But it doesn't seem to be working for Wisps for some reason. Is this supposed to be intentional or is it just bugged?

**Comment by MNoya** [comment]
> Using the Select all other units hotkey should select every unit that is not your main hero

Currently it will only target the main city center. Not really concerned in making this hotkey work, instead "Select all Idle builders" and "Select all idle army" should have their own hotkey, via the Idle Builders/Idle Army (in the future)
