### ISSUE TITLE
Cannot start game properly

### ISSUE THREAD

**Issue by ssnl** [MNoya/DotaCraft#26]
**Summary:**

title

**Repro Steps:**
1. start a game on the 2-player map
2. lock+start

**Result:**

![1](https://cloud.githubusercontent.com/assets/5674597/9701264/f65a123c-53d5-11e5-8cb7-69625bc67b54.png)

**Expected Result:**

game starts

**Note**
- I didn't see this issue before the 9/1 or 9/4 update. I don't remember which one.
- After quitting the game, I started a bot match. In hero choosing screen, antimage has the name demon hunter, sf is called firelord, and kotl is archmage, etc.

**Comment by MNoya** [comment]
> After quitting the game, I started a bot match.

That's a Valve issue they need to fix :sweat:

Thanks for the report, we haven't tested the new spawn-ingame method with multiplayer, it's busted.
