### ISSUE TITLE
CTD while trying to select Peasants and the Town Hall training one.

### ISSUE THREAD

**Issue by justSQL** [MNoya/DotaCraft#27]
**Summary:**

Selecting (with left click) an x amount of Peasants and a town hall producing a peasant leads to CTD once the Peasant's training timer hits 0. See screenshot for more accurate description: https://i.imgur.com/S2YbPg0.jpg

**Repro Steps:**
1. Load DotaCraft, and pick Human. (I've been using Hills of Glory as the map)
2. Start training a peasant in the Town Hall
3. Hover over the Town Hall and the peasants that spawn when the game starts. (As is seen on the screenshot earlier) Do not release the left mouse button.
4. As the Training timer hits 0, the client CTD's.
5. If that isn't the case, try training a few more peasants while following these steps - and select the peasants you already managed to train too. (For me it takes 7 peasants ingame, and one being trained)

**Result:**

The client CTD's

**Expected Result:**

The client doesn't CTD.

**Comment by justSQL** [comment]
So, i noticed that this crash does not only occur when peasants spawn and you're painting a selection box over them. I recorded a video, which should say more than my words; http://webm.host/1e464/
No idea what could be causing this.

**Comment by MNoya** [comment]
More http://sendvid.com/pvxcvpqp
