### ISSUE TITLE
Nightelf attackable buildings do not attack when they are enrooted

### ISSUE THREAD

**Issue by dun1007** [MNoya/DotaCraft#278]
**Expected behavior:** Building should attack enemy units automatically as long as they are in melee range

**Current behavior:** Buildings do not attempt to attack enemies at all, and only react to enemy attacks. Also, they stop backswing animation halfway through and return to idle state.

**Comment by MNoya** [comment]
Interesting, it's actually a problem with the testing commands that spawn units in the Neutral team, it worked fine for non neutral units (via _-createhero name enemy_, for example). In the process of finding this out, I did make changes to the units/attacks.lua file that had a problem with `script_reloading` not refreshing the scripts in the aggro filter, its now split in 2 files: _aggro_filter_ and _attack_modifiers_
