### ISSUE TITLE
Wisp ignoring gather order to an occupied tree

### ISSUE THREAD

**Issue by Arhowk** [MNoya/DotaCraft#28]
If you issue a wisp to build something from a tree, other wisps can't harvest wood from that tree.

**Comment by MNoya** [comment]
Yep I had this marked, but need a way to reproduce it
![img](http://puu.sh/k2h7R/27165d24db.png)

**Comment by MNoya** [comment]
Kinda intended, but I agree it needs the redirection, like mentioned in #24
