### ISSUE TITLE
Invalid Truesight abilities

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#285]
Newest sentry ward works, but the following aren't revealing invis:
- Flying Machine passive truesight
- Arcane Tower magic sentry,
- Arcane Tower reveal

**Comment by dun1007** [comment]
Truesight aura on point has a bug, causing true sight on area to last forever. Commented out thinkers and implemented dummy approach in far_sight.lua temporarily

**Comment by MNoya** [comment]
Gotta review all usages of CreateThinker in other abilities aswell
