### ISSUE TITLE
Haunted goldmine shows 1/5 acolytes attached when none are

### ISSUE THREAD

**Issue by DBX5** [MNoya/DotaCraft#290]
as shown in the picture below for some reason the haunted gold mine shows one acolyte already attached even though none of them are.

![ud gold mine claims 1 unit already in when 0 are in](https://cloud.githubusercontent.com/assets/20033227/16547268/92c12046-411c-11e6-8831-3473c217277a.jpg)

repo steps

1: add acolytes to mine
2: remove acolytes from mine
3: repeat till bug produces

this is what should happen
1: add units shows the number of units attached
2: remove units shows no units attached

**Comment by MNoya** [comment]
I can't repro this anymore but there are more problems with acolyte gold mining, currently:
- [x] They are invulnerable but shouldn't.
- [x] There can be more than 5 (there should be a warning message and a move-to-follow order)
- [x] `Attempted to create unknown modifier type modifier_gathering_gold!` console error
- [x] Killing them (tested via -kill) doesn't empty a slot on the mine
- [x] Gather should have priority over repair
