### ISSUE TITLE
Items with charges do not get refreshed when moved to new hero

### ISSUE THREAD

**Issue by DBX5** [MNoya/DotaCraft#291]
rod of Necromancy does not refresh when handed to another hero who hasn't used it yet, cant test other items since they dont appear to be available yet.

Repo

1: kill unit
2: use rod of necromancy (goes on cd)
3: move item to secondary hero
4:  CD continues on other hero

how it should work
1: Kill unit
2: use rod of Necromancy (goes on cd)
3: move item to secondary/allied hero
4: cd removed
5: use rod of necromancy (stars new cd)
6: pass item back to original hero (original cd on that hero should continue)

**Comment by MNoya** [comment]
Won't fix this one as it's kinda hard and doesn't have that much repercusions (if you want to use the item on the secondary hero, just move it before using the other)
