### ISSUE TITLE
Corpse summon crash

### ISSUE THREAD

**Issue by Califax526** [MNoya/DotaCraft#298]
Crashes the game when summoning ability requires a corpse.
- [x] DK - Animate Dead
- [x] Crypt Lord - Beetle
- [x] Warden - Vengeance
- [x] Blood Mage - Phoenix

---

Reviewed
- [x] Paladin Resurrection
- [x] Undead Necromancer Raise Dead, Item Rod of Necromancy
- [x] Undead Graveyard Exhume Corpses

---

To Fix:
- [ ] Undead Meat Wagon Get Corpse, Drop All Corpses, Exhume Corpses
- [ ] Orc Spirit Walker Ancestral Spirit
- [ ] Ghoul Cannibalize

**Comment by MNoya** [comment]
Thanks for the report, I recently changed the system and forgot to review the abilities involved.
