### ISSUE TITLE
Peons get stuck on gold mine after several trips

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#30]
Not sure if it's an issue with the pathing of the peon or the mine model itself. There appears to be a blocked area to the right of the mine entrance. http://imgur.com/L7exjeb 

Note: This only seems to happen with gold mines oriented such as the one in the picture.

**Comment by MNoya** [comment]
Nice find. The positions towards the mine are randomized near the mine entrance, and it seems that for some angles the peon would never reach it.

**Comment by MNoya** [comment]
![img](http://puu.sh/lAtZU/2f0dc5a922.jpg)
