### ISSUE TITLE
Item pick up crash

### ISSUE THREAD

**Issue by Califax526** [MNoya/DotaCraft#301]
**Summary:**

Game crashes when you drop an item from your inventory, and pick up new one right after it.

**Repro Steps:**
1. Select Alchemist with 6 items and Footman.
2. Have some space between you and pickable item.
3. Drop 1 Alchemist's items next to the pickable item. (Alchemist should run to the location, while Footman stays still)
4. Right after you drop it, pick up the pickable item.
5. Game crashes.

In picture I dropped Vitality Booster right below Cloak of Shadows, and picked it up as fast as I could.

![123123](https://cloud.githubusercontent.com/assets/20010714/16635812/d3974a74-43dc-11e6-97c0-4e695d7658e9.png)

**Comment by Califax526** [comment]
Also happens if you pick up tomes, still can't constantly produce it. :(

**Comment by MNoya** [comment]
The problem still persists

https://www.youtube.com/watch?v=OAQ0TkmFaNs crashes at 1:10
-testhero alchemist
-testunit footman
-iseedeadpeople (not required)
-whosyourdaddy (not required)

**Comment by MNoya** [comment]
We tried this for like 10 minutes in a 1v1 lobby, didn't manage to get a crash :(

**Comment by MNoya** [comment]
Still happening
