### ISSUE TITLE
Update attack types

### ISSUE THREAD

**Issue by Califax526** [MNoya/DotaCraft#318]
| Unit | Current attack type | What it should be |
| --- | --- | --- |
| Brewmaster's Fire Panda | Hero | Normal |
| Brewmaster's Earth Panda | Pierce | Normal |
| Demon Hunter (Metamorphosis) | Hero | Chaos |
| Pitlord | Chaos | Hero |

Dread Lord's Infernal **ARMOR TYPE** from Hero to Heavy

**Comment by MNoya** [comment]
Nice job finding those, good catch!
