### ISSUE TITLE
Stutter-stepping with certain abilities causes FPS drops

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#32]
For example, stutter stepping with shadowmeld or mount hippogriff with nightelf archers causes FPS to tank. Sometimes this causes the game to crash. During this testing I was the host of the game, as well as the only player.

Also once the game reaches around 100 units average FPS halves (23 -> 10). 

Keep in mind my PC is basically wood (laptop i3 processor, intel integrated graphics, 4gb ram).

**Comment by dun1007** [comment]
I think it's kinda hard to go around this since mount has to reposition archer on the back of hippey every frame

**Comment by MNoya** [comment]
Nah it's just a single SetParent, the problem comes from finding units in radius every time you press the skill, it could just skip the 2nd+ cast if the current hippo is still valid.
