### ISSUE TITLE
Right Clicking While Selecting Uprooted Structure Triggers Waypoint Change

### ISSUE THREAD

**Issue by dun1007** [MNoya/DotaCraft#329]
**Reproduction:**
1. Uproot a NL structure
2. Right click somewhere on the map to move

**Expected Behavior:**
Selected structure moves to clicked location but does not change waypoint

Needs a check whether structure is uprooted or not in building library

**Comment by MNoya** [comment]
Easy fix, bug was introduced with 4b3dd1e09fa2a5ad58d84ffb4b0ba56c9b3e7ff1 to prevent casting things on uprooted buildings as if they were not buildings.
