### ISSUE TITLE
Uproot Does Not Change Collision Radius of Structure

### ISSUE THREAD

**Issue by dun1007** [MNoya/DotaCraft#330]
Uprooted structure should be slim enough to walk through a path as wide as one tree(64)

https://youtu.be/xrBHIj8rCG4?t=1h26m35s

**Comment by MNoya** [comment]
Completely forgot about this, it's quite important!

**Comment by dun1007** [comment]
Standard NE strategy 4Head

**Comment by MNoya** [comment]
Pesky elves ![img](http://puu.sh/q9Yj6/c9caf56f4f.jpg)
