### ISSUE TITLE
Priest's Inner Fire only targets 1 unit

### ISSUE THREAD

**Issue by Califax526** [MNoya/DotaCraft#332]
**Summary:**

Priest's Inner Fire keeps refreshing the duration, and won't change the target.

Default state of Inner Fire dosen't work at all (when you spawn fresh new Priest). You have to manually cast it once, to order to work.

**Repro Steps:**
1. Have group of 4 units + priest.
2. Cast Inner Fire manually to unit 1.
3. Priest will only Inner Fire unit 1, every time the ability is off cooldown.

**Expected Result:**

Once unit 1 is Inner Fired, it should change the target to unit 2 and so on.
And shouldn't target units that have Inner Fire already.

**Extra stuff**

Maybe you could make Heal and Inner Fire same way as Destroyer's abilities, pretty sure you can't have both active at the same time in WC3.

**Comment by MNoya** [comment]
I need to review all the abilities which have an autocast and make sure they all follow the same logic:
- Sorceress Slow
- Priest Heal and Inner Fire (only 1 active)
- Spell Breaker Spell Steal
- Shaman Bloodlust
- Dryad Abolish Magic
- Druid of the Talon Faerie Fire
- Crypt Fiend Web
- Necromancer Raise Dead
- Banshee Curse
- Obsidian Statue Essence of Blight/Spirit Touch (only 1 active)
- Warden Avatar of Vengeance Spirits
