### ISSUE TITLE
Blademaster should be able to attack while spinning

### ISSUE THREAD

**Issue by Califax526** [MNoya/DotaCraft#341]
Basically ~~there shouldn't be any auto-attack related restrictions while spinning.~~
- ~~You can attack normally, and it deals damage.~~
- All modifiers "should" work. (Only tested Orb of Venom)
- By default "auto attack: always", he should start attacking while spinning.

**Comment by MNoya** [comment]
Ok so this ability is weird, it should apply orbs like normal attacks but no attacks are actually made (no matter what the damage of the hero is, the hero won't do more than the ability damage to any enemy unit around him). It should allow right clicking units and should aggro-move to units nearby.
