### ISSUE TITLE
Root "highlight" model and spinning gold mine

### ISSUE THREAD

**Issue by Califax526** [MNoya/DotaCraft#348]
https://www.youtube.com/watch?v=JZccYbXVMdc

**Root "highlight" model**
- After selecting Tree of Life's root ability, other root abilities show its model.

**Spinning gold mine**
- Gold mine turns or "faces" towards Wisps, when manually "loading" them.
- Not 100% sure what causes it, but it always happens after the root thing ^

**Comment by MNoya** [comment]
Good catches as always! Thanks for the repro video, it's really helpful.
