### ISSUE TITLE
Map Names do not indicate max players

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#35]
Just as the title says, the map names don't indicate how many possible players there are for each map, nor the 'About' section.

**Comment by MNoya** [comment]
Yeah we totally need a good way to view map count, probably a (X) at the end of the map name should suffice.

**Comment by MNoya** [comment]
Refer to https://github.com/MNoya/DotaCraft/wiki/Adding-New-Maps
