### ISSUE TITLE
Undead_sacrificial_pit is not placeable

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#36]
The building displays the preview, but will not be placed.
**_Console Log:**_
`[BH] AddBuilding undead_sacrificial_pit
Unknown Damage type during parse! (DAMAGE_TYPE_PHYSICAL)
CDOTA_ParticleManager::SetParticleControlEnt: Unable to lookup attachment follow_origin on model models/props_structures/cage001.vmdl
prop_dynamic at (0.000, 0.000, 0.000) has no model name!
ERROR: RESOURCE_TYPE_MODEL resource 'models/error.vmdl' (BC8F62FD531EF4EF) requested is not loaded and may have been deleted.
GetNumPrecachedBreakablesForProp discovered no precached break models for model "models/error.vmdl".
Ensure PropBreakablePrecacheAll was called first.
Player 0 Lumber: 1338
895
Player 0 Lumber: 1358
Return Resources of type    lumber
Send Build command. Queue: false
CCustomGameEventManager::ReceiveCustomGameEvent_ClientToServer
  Args:  {
  X float( -5533.934570 )
  Y float( 2734.328613 )
  Z int( 384 = 0x180 )
  Queue int( 0 = 0x0 )
}
[BH] Build Command - Queued:    false
[BH] Blight check for undead_sacrificial_pit:   true
[BH] AddToQueue undead_acolyte 581 -> location [-5536, 2720, 384]
Script Runtime Error: ...6109224\396109224.vpk:scripts\vscripts\units\builder.lua:94: attempt to perform arithmetic on field 'CollisionSize' (a nil value)
stack traceback:
    ...6109224\396109224.vpk:scripts\vscripts\units\builder.lua:94: in function 'onBuildingPosChosen'
    scripts/vscripts/libraries/buildinghelper.lua:947: in function 'AddToQueue'
    scripts/vscripts/libraries/buildinghelper.lua:76: in function <scripts/vscripts/libraries/buildinghelper.lua:54`

**Comment by MNoya** [comment]
It's missing a CollisionSize, gotcha. Nice finds!
