### ISSUE TITLE
Haunted mines sometimes do not properly take in a fifth acolyte

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#37]
If you take one acolyte off a full mine, then put it back on, it does not always take it. The gathering ability on the acolyte is toggled, but it does not remove it from selection and it does not contribute to gold gain. It appears the mine thinks it is full (based on console spew), despite the overhead showing 4/5 acolytes.

Note: It does appear that the jobless worker notification does count the acolyte as jobless.

**Comment by MNoya** [comment]
Any way to reproduce it? It has to be some faulty OnOrder skip not removing the builder properly from the list.

**Comment by AardvarkLaurant** [comment]
The way I've done it is fill up a mine, then remove the right-most acolyte, do something with it, then send it back. Sometimes it does go back alright, but sometimes it just runs around the mine trying to get in. When I did this I also had many ghouls (say 20-30 at most) harvesting trees, not sure if that's relevant.
