### ISSUE TITLE
Neutrals lose acquisition aggro after first engagement

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#372]
Repro steps:
1. Aggro a camp by walking nearby
2. Run away until they leash out
3. Walk again to aggro the camp

Result: Neutrals don't aggro on proximity anymore, only if attacked.
Expected result: Neutrals keep their behavior after the first engagement no matter what.

**Comment by d3nyme** [comment]
![20161031210455_1](https://cloud.githubusercontent.com/assets/22402528/19855123/d751e6ba-9fad-11e6-8ea0-6a4374b715ce.jpg)

is this the same issue?

**Comment by MNoya** [comment]
Looks like it. I already have a fix for this :)

**Comment by MNoya** [comment]
Fixed in 108fd49c643a08602d8d0d64e740f18aaa2db929
