### ISSUE TITLE
First tavern hero requires Altar

### ISSUE THREAD

**Issue by d3nyme** [MNoya/DotaCraft#375]
Result: First tavern hero can be purchased without an Altar.
Expected: First tavern hero requires any Altar.

**Comment by d3nyme** [comment]
![20161101043927_1](https://cloud.githubusercontent.com/assets/22402528/19871418/c7fdb274-9fef-11e6-9755-c8a10e972ae8.jpg)

**Comment by MNoya** [comment]
The problem comes from counting the altar before it finishes
