### ISSUE TITLE
Heroes unable to level up after level 5

### ISSUE THREAD

**Issue by d3nyme** [MNoya/DotaCraft#377]
Experience bar will not increase after killing enemies.

**Comment by MNoya** [comment]
This should happen when attacking neutrals, there needs to be player-controlled enemies in order to get past level 5.

In case you are playtesting heroes, check the developer cheat list: https://github.com/MNoya/DotaCraft/blob/master/game/dota_addons/dotacraft/scripts/vscripts/developer.lua
