### ISSUE TITLE
Ghoul automatic tree harvesting does not check the path to the tree

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#38]
Ghouls may sometimes choose a tree that can't be pathed to (because other trees are in the way), and as a result, will stand at a point close to the tree as possible and idly look at it until the path becomes cleared. This effect may apply to human workers too if they use the same harvesting AI.

**Comment by MNoya** [comment]
They do. Whe this happens, type `debug_trees` and check the screen to see what's going on

**Comment by MNoya** [comment]
#181
