### ISSUE TITLE
You can train more than one hero with lvl 1 main building (great hall etc.) if you have enough resources

### ISSUE THREAD

**Issue by Coolkip** [MNoya/DotaCraft#39]
If you have enough resources to afford a secondary hero, while you are training your first one you can qeue the next one and even a third one. 
1. Build altar and don't level your main building.
2. Get enough resources to afford the second hero.
3. Start the training of your first hero.
4. While you are training your first hero, click on another hero and he will get qeued.
5. Enjoy having all your heroes with lvl 1 base.

**Comment by wfzyx** [comment]
Paging @MNoya I think we just need a hall level check close to [this line](https://github.com/MNoya/DotaCraft/blob/master/game/dota_addons/dotacraft/scripts/vscripts/buildings/queue.lua#L26)

**Comment by MNoya** [comment]
This was actually just a problem with Orc Altar abilities missing on the tech tree, will fix it next
