### ISSUE TITLE
Workshop for reborn.

### ISSUE THREAD

**Issue by lilezek** [MNoya/DotaCraft#4]
As far as there isn't any button for suggestions in github I open an issue. Do you have in mind to upload to workshop this piece of code (even if it is unfinished) so we can see the progress within the client?

**Comment by MNoya** [comment]
I won't upload a public version to the workshop until this is in a good playable state, and there's still a lot of content to add unfortunately. 

If you really want to peak at it and act as a pre-alpha tester, I can update the private version in a couple of days and let you know (needs Steam invite), or you can just download the whole repo, merge the /game and /content folders with yours at the /dota 2 beta/ folder and you'll have access to the game files in Reborn workshop tools :)

**Comment by lilezek** [comment]
Do I need any kind of knowledge to do so (upload it to the reborn workshop I mean)? I know Lua and I'm an experienced programmer but this framework is new to me.

**Comment by MNoya** [comment]
Add me on Steam /id/mnoya

**Comment by lilezek** [comment]
Done, waiting for you reply from steam. You can close this issue if you find my friendship invitation.
