### ISSUE TITLE
Shop not working

### ISSUE THREAD

**Issue by Coolkip** [MNoya/DotaCraft#41]
Shop opens, but I can't buy anything.
1. Build a shop/ go to the tavern
2. Click anything with left/right mouse button
3. Nothing works

**Comment by MNoya** [comment]
@Infekma Not really sure what could cause [this](https://trello.com/c/JN3HQUVl/79-tavern-sendcustomgameevent-is-empty-in-live-version-works-fine-in-tools)

**Comment by MNoya** [comment]
Turns out we were registering the dynamic wrap registering incorrectly, this is how it's done:

```
if not unit_shops then
    unit_shops = class({})

    --never register here  
end 

function unit_shops:start()
    unit_shops.Units = {}

    -- register here
    CustomGameEventManager:RegisterListener( "Shops_Buy", Dynamic_Wrap(unit_shops, "Buy"))
end

--- stuff

-- final line
if not unit_shops.Units then unit_shops:start() end
```
