### ISSUE TITLE
Graveyard isn't detected

### ISSUE THREAD

**Issue by Coolkip** [MNoya/DotaCraft#42]
I couldn't build\create anything which require graveyard, but I already built one. When I had built another graveyard, I could build/create these things. 
1. Player 2 was undead (as was player 1) 
2. Build a graveyard
3. You can't "use" the graveyard to make for instance crypt fiends
4. Build a second graveyard
5. Now you can

(When one graveyard is destroyed the effect is reverted, you CAN'T make let's say crypt fiends when one of your graveyards is destroyed)

**Comment by MNoya** [comment]
Issue with not updating the building requirements fast enough. Good find
