### ISSUE TITLE
Incorrect stat adjustments

### ISSUE THREAD

**Issue by Tethrinaa** [MNoya/DotaCraft#44]
in your npc_items_custom.txt (and applier file associated with it) :

MODIFIER_PROPERTY_MANA_REGEN_CONSTANT should be used instead of MODIFIER_PROPERTY_BASE_MANA_REGEN

The one you are using is giving a 1% bonus (I think? some percent anyway) per point of int instead of +.01 base (think like how crystal maiden grants flat amount of mana regen)

MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE should also be MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE, to prevent it from showing as a red negative number in the tooltip (unless you handled this elsewhere, I'm commenting from my own derivative usage, and not from playing your dotacraft, so I apologize if you handled them elsewhere)

**Comment by MNoya** [comment]
`MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE` is good for base damage increase, but yeah I guess it doesn't work well with negative values. I don't see any issue with this

You are right on the Mana regen constant though, Dota heroes' `MODIFIER_PROPERTY_BASE_MANA_REGEN` is just 0.01 and it's actually the mana_regen_constant of 0.04 that needs to be updated to 0.05 in this case.
