### ISSUE TITLE
Units don't automatically detect enemies after one A-click

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#45]
For example, I attack-move (on the ground) my army at a group of neutrals; each unit attack its target until the target dies, then does not find another target even though their fellow units are being attacked by the aggro'd neutrals. 

I only have done this with the Orcs so far, but I assume each race uses the same AI for determining targets automatically.

**Comment by MNoya** [comment]
This is because of how the current rewritten attack system works, it needs to be changed to a smarter system but it's hard :smile:

**Comment by MNoya** [comment]
Fixed in 623c20167b960bedc749715750d1aa944de28f1a
