### ISSUE TITLE
Builder gold collecting script error

### ISSUE THREAD

**Issue by poonwu** [MNoya/DotaCraft#5]
My dota client raise a script error when I tried to collect some gold with some builders.
https://github.com/MNoya/DotaCraft/blob/master/game/dota_addons/dotacraft/scripts/vscripts/units/builder.lua#L660

Apparently, `FindClosestResourceDeposit( caster, "gold")` returns nil.

I believe there's some typo at https://github.com/MNoya/DotaCraft/blob/master/game/dota_addons/dotacraft/scripts/vscripts/units/builder.lua#L847

Shouldn't it be similar to its lumber's counterpart? https://github.com/MNoya/DotaCraft/blob/master/game/dota_addons/dotacraft/scripts/vscripts/units/builder.lua#L858 ?

**Comment by MNoya** [comment]
Yep, I've been testing nightelves and those don't return gold so it went unnoticed, fixed in @8e70fb691f3cc41ceb85cc985c1679f59bbedee4
