### ISSUE TITLE
Orc building research abilities finish instantly, and don't consume lumber

### ISSUE THREAD

**Issue by AardvarkLaurant** [MNoya/DotaCraft#53]
This applies to all buildings but the primary structure. The channeling bar appears briefly then goes away, giving units the upgrade. 
Note: All buildings don't take the required lumber away

**Comment by Chillaxxx** [comment]
i can confirm

**Comment by AardvarkLaurant** [comment]
This applies to Humans too

**Comment by MNoya** [comment]
Fixed in 067a0006425468a86bd575c7ed4bc95e5d54fd28
