### ISSUE TITLE
Cannot entangle gold mines

### ISSUE THREAD

**Issue by Coolkip** [MNoya/DotaCraft#54]
When I built a tree of life next to a gold mine, it didn't entangle it. Tried it at 2 gold mines and it didn't work.

**Comment by MNoya** [comment]
You mean auto entangle, right? If you manually entangle does it work?

**Comment by Coolkip** [comment]
How do I manually entangle?

**Comment by MNoya** [comment]
Uproot -> Use the active entangle on a mine
