### ISSUE TITLE
Footman defend ability only affects one unit in group

### ISSUE THREAD

**Issue by ravenguard98** [MNoya/DotaCraft#68]
If there are several human footman units selected only one will activate defend when the skill is toggled on, whereas in Warcraft 3 all units in the group would toggle it on.

**Comment by ravenguard98** [comment]
Also the same with toggling priest heal in groups, so probably same with all group selection skill interactions.

**Comment by MNoya** [comment]
Yeah somehow activating the autocast doesn't trigger an order that can be catched by the filter, so it will be hard to replicate "Enable Autocast on everyone".

Thanks for the report, Footman Defend is missing the MultiOrder key system
