### ISSUE TITLE
Build structure + waypoint queue cancels structure

### ISSUE THREAD

**Issue by myrontay** [MNoya/DotaCraft#72]
**Summary:**

Queuing the peasant to build a structure then waypoint to a location results in the structure not being built.

**Repro Steps:**
1. Queue structure build then waypoint to any location

**Result:**
1. Peasant walks to the structure location
2. Peasant starts the build animation
3. Nothing appears
4. Peasant walks to the waypointed location

**Expected Result:**
1. Peasant to walk to the structure location
2. Peasant builds and finishes structure
3. Peasant walks to the waypointed location

**Comment by MNoya** [comment]
What do you mean waypoint queue, Shift+Queue move?

Haven't made the building library be able to queue movements yet, that's gonna be a hard one :smile:

**Comment by myrontay** [comment]
Oh I thought u did. I was able to queue the peasant movement. i.e. queue move orders to different locations with shift click.. Just that when I tried mixing the building construction in with the move orders it bugged out the construction.
