### ISSUE TITLE
Peasants automatically added to selection when spawned

### ISSUE THREAD

**Issue by myrontay** [MNoya/DotaCraft#73]
**Summary:**

Peasants are automatically added to selection when spawned. If player is selecting a structure then the peasant automatically gets selected when spawned. If player is selecting a unit then the peasant automatically gets added with the selection so the player is now selecting peasant+unit.

**Repro Steps:**

a. Select structure
b. Select unit

**Result:**

a. Peasant gets selected
b. Peasant + unit gets selected

**Expected Result:**

a. Selection of structure continues
b. Selection of unit continues

**Comment by MNoya** [comment]
This is caused by this dota setting:

![img](http://puu.sh/kFOPl/d85caecf50.png)

**Comment by myrontay** [comment]
Ah... that makes sense since the peasant is treated as a summon. Hmm... guess nothing much can be done about that then.

**Comment by MNoya** [comment]
`dota_player_add_summoned_to_selection 0`

I can force this setting as the default. Should I?

**Comment by myrontay** [comment]
Yes. Coz most of the time the default settings people use is for the main
dota game. But those wont translate well into some custom games.
