### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by myrontay** [MNoya/DotaCraft#74]
**Summary:**

Area selection attempt on peasants results in game crash. Tried this 3 times and all 3 times it happened.

**Repro Steps:**
1. Have 5-10 Peasants harvesting the gold mine (walking back and forth from gold mine to Town Hall)
2. Hold+Left click drag to attempt to select the Peasants

**Result:**

Dota crashes

**Expected Result:**

Peasants to be selected

**Comment by MNoya** [comment]
Similar to #27 . Probably has to do with the selection filter, thanks for the repro, good catch!

**Comment by myrontay** [comment]
Np!
