### ISSUE TITLE
Neutrals (Turtlerock)

### ISSUE THREAD

**Issue by TwiGzZz** [MNoya/DotaCraft#75]
The following Neutrals are used in Turtlerock.
Sea Turtle Hatchling
Sea Turtle
Giant Sea Turtle

Ogre Warrior
Ogre Magi
Ogre Lord

Forest Troll Trapper
Forest Troll
Forest Troll Berserker
Forest Troll Warlord

Murloc Nightcrawler
Murloc Huntsmen

**Comment by MNoya** [comment]
Done in f64ccb97bf360c5bdd99e5d79a1ed434936839f4
