### ISSUE TITLE
Neutrals Minimap Icon

### ISSUE THREAD

**Issue by TwiGzZz** [MNoya/DotaCraft#77]
The minimap icons from cleared camps are not getting removed.

Suggestion:
Search for all units around the minimap icon in x aoe on start. Once the camp is cleared the icon gets removed for all players that had vision on it after clearing.

**Comment by MNoya** [comment]
"Icon gets removed for some players" isn't as easy as you think, it requires multiple instances of the icon to be active for all camps, haven't dealt with it yet but it also requires to handle when a player 'discovers' a camp that was now cleared

I expected Valve to expose their Neutral icons by now, but it seems that we'll just have to make them ourselves

**Comment by MNoya** [comment]
Adding to this, currently the icons are incorrectly getting removed when spawning a base, giving away the enemies positions.

**Comment by MNoya** [comment]
Reopened as it was broken by a Dota update

Currently minimap icons will only hide after both players have discovered the killed camp, because the enemy camp icon is visible to all teams
