### ISSUE TITLE
Tree of Ages angles

### ISSUE THREAD

**Issue by TwiGzZz** [MNoya/DotaCraft#79]
The "Tree of Ages" is rotated by 180°.

![lvl1](https://cloud.githubusercontent.com/assets/15113833/11021453/d316a440-8641-11e5-898a-1459fb91ba7b.png)
![lvl2](https://cloud.githubusercontent.com/assets/15113833/11021454/d3e4b4fc-8641-11e5-9bf1-55bef3072535.png)
![lvl3](https://cloud.githubusercontent.com/assets/15113833/11021455/d4e79964-8641-11e5-89c6-9f51783af62d.png)

**Comment by MNoya** [comment]
Caused by the Upgrade not remembering the angle the unit was facing before replacing to the new one
