### ISSUE TITLE
Missing Neutral Features

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#94]
- [x] Item Drops 5523488879f82ef6d0662ffe134b4242c9368eeb
- [x] Goblin Merchant 8e22b717962acffef70d6b46ad2e14d2fab0215f
- [x] Goblin Laboratory
  - [x] Sapper 768900c764a613713dd74643d037f5f7c3219cee
  - [x] Zeppelin c9e5459140bda66037cc2bd329ff8bbc5689be85
  - [x] Shredder 0dc322a9de5618b2403084784aed01d98cbb362b
- [x] Mercenary Camp d4fb8deb974b2ebbfeb6c03665ab07879df521c1
- [x] Marketplace
- [x] Abilities
- [x] Fountain of Health/Mana
- [x] Improved AI

**Comment by TwiGzZz** [comment]
The "Goblin Merchant" is missing in the list.

**Comment by MNoya** [comment]
Added! Now that the Tavern works, it should be easy to make different shop lists

**Comment by MNoya** [comment]
- Level 6+ Creeps also have Hero Magic Resistance
  As special units, Level 6+ Creeps and Heroes enjoy a limited magic resistance against enemy spells. Negative spells cast on a 6+ Creep last a shorter duration than if cast on a lower level Creep.
- Level 7+ Creeps
  Level 7+ Creeps are smarter than level 1-6 Creeps. The "smart" Creeps behave like melee AI units. In particular, these Creeps:
  - Tend to attack injured units before healthy ones.
  - Intelligently prioritize Heroes in attack range.
  - Attack buildings under construction.
  - Level 7+ Creeps all deal Chaos damage.
  - Creeps will run from towers as they drop below 60% life. Creeps are very aggressive with towers.
